apiVersion: v1
kind: Service
metadata:
  name: actions-api
  namespace: actions
  labels:
    app: actions-api
    team: team6
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    app: actions-api
